Add version of buffer that works without seek
fo-dicom/fo-dicom pull request #1253
Opened 2021-11-03 18:37 UTC by mrbean-bremen

- proof of concept only, work in progress

#### Checklist
- [x] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [ ] I have updated API documentation
- [ ] I have included unit tests
- [ ] I have updated the change log
- [ ] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
This is an attempt to handle no-seek streams by adding a buffer to the stream source that handles the Mark/Rewind part. This is only partly implemented, and works for the artificial dataset in the test (haven't tested sequences yet, but I think that they won't work due to the missing milestone support).

The goal is to have a possibility to read this kind of data (which I think is going to be more important with time) without a large memory impact, and without impacting the normal reading with seek.
Before proceding I wanted to know if this makes sense at all. We already discussed this in #1218 with the result that it may not be worth it, but I wanted to give it a shot after thinking a bit more about this...

Feel free to dismiss this, I have no problems with just throwing that away 😄

2021-11-03 18:39 UTC, mrbean-bremen commented on Tests/FO-DICOM.Tests/DicomFileTest.cs
> +            }
This check probably won't handle sequences properly, I haven't checked.

2021-11-07 19:48 UTC, mrbean-bremen commented
This is now ready for review. It turned out to be less complicated than I thought, because the stream supports getting the length, and I can just reuse the existing milestone support (for some reason I thought it allowed a recursive mark/rewind, but fortunately it is much simpler).
I added a test with a small SR which has multiple nested sequences to make sure that these are handled correctly, additionally to the artificial dataset which has all VRs. These are not exhaustive tests (only some types will be read from the buffer), but as the handling of the different types is basically the same it may be sufficient.
I also checked that the buffer usually does not get larger than 132 bytes (the preamble), though with large sequences it may get larger.

2021-11-08 15:03 UTC, amoerie commented on FO-DICOM.Core/DicomItemComparer.cs
> +                    if (!new DicomDatasetComparer().Equals(dataset1, dataset2))
Feels a bit wasteful to always create a new comparer here. When you sort a large array or list, .NET will call .Equals quite a lot.

2021-11-08 15:14 UTC, mrbean-bremen commented on FO-DICOM.Core/DicomItemComparer.cs
> +                    if (!new DicomDatasetComparer().Equals(dataset1, dataset2))
As far as I understand, this is only used in tests (it is not an implementation fir `DicomDataset.Equals`), so I didn't really check much for performance.

2021-11-09 09:24 UTC, gofal approved these changes

2021-11-11 14:21 UTC, mrbean-bremen commented
> you changed this to "draft" for a reason?

Yes, sorry, I thought I added a note. I tested some more files with different transfer syntaxes, and some are not working (commented out in the test). I have to understand and fix this first... will see if I get to it tonight, or over the weekend.

2021-11-15 09:04 UTC, mrbean-bremen commented
Just to give an update: I fixed a couple of problems, but there is still one dataset that does not work correctly (something to do with the length of a sequence, GH133) which I have to understand and fix.
There are two things that are not so nice:
- delayed handling of large tags is not supported, if it is set, it will be changed to ReadAllTags (I don't think we can do anything about this without the possibility to seek in the stream)
- for deflated transfer syntax, the stream is directly used - I now use a copy of the not yet processed part of the stream, which is not nice, but I'm not sure how to prevent this; we can probably live with that as this is not often used

2021-11-15 19:10 UTC, mrbean-bremen commented
Ok, that turned out to be a dumb mistake with milestone handling - now fixed. Works now at least with all test files that the normal file also works with, with the mentioned caveats. There are a few files that don't work with either stream, I think at least one of them shows the problem that @amoerie has already fixed - I will check that, but outside of this PR.

2021-11-15 19:27 UTC, mrbean-bremen commented
Update: I checked the files that don't work for either stream, and they are not problematic - the problems are all due to invalid DICOM.

2021-11-16 18:48 UTC, mrbean-bremen commented
This is now ready for review (again). Note that this PR does not change any existing behavior, it only adds handling of streams without seek capability (input for risk assessment 😀). 

Unrelated: I accidentally (due to a failing test in the next-to-last commit) found that reading a memory mapped file creates an additional (0000, 0000) entry in the dataset due to the fact that EOF is not correctly detected, and parsing continues after the data end (where all bytes are 0, though I'm not sure if this is guaranteed). Is this a bug or expected behavior?

2021-11-18 21:33 UTC, amoerie commented
> Unrelated: I accidentally (due to a failing test in the next-to-last commit) found that reading a memory mapped file creates an additional (0000, 0000) entry in the dataset due to the fact that EOF is not correctly detected, and parsing continues after the data end (where all bytes are 0, though I'm not sure if this is guaranteed). Is this a bug or expected behavior?

This might be the same issue I had with the invalid DICOM files. Fellow Oak DICOM definitely parses files differently from MicroDicom or dcmdump, because both these files reject / throw an error when I opened a file with gibberish at the end, while DicomFile.Open just worked. The parser seems to make a "best effort" in trying to make sense of things, and just throws the towel in the ring at some point. However, all successfully read tags are usable, so I guess it's not a bad feature. It does however make it harder to detect corrupt files.

2021-11-19 09:07 UTC, amoerie requested changes
Review ready, mostly questions but some suggestions too. Looks pretty good! 

I hope the test coverage is sufficient, because there is quite some complexity in the _buffer management in NoSeekStreamByteSource...

2021-11-19 09:07 UTC, amoerie commented on FO-DICOM.Core/IO/NoSeekStreamByteSource.cs
> +            lock (_lock)
Does NoSeekStreamByteSource need to be thread safe?? Is this being called from multiple threads?? If so, I think the rest of the implementation is very prone to multithreading issues. If not, why the lock?

2021-11-19 19:17 UTC, mrbean-bremen commented on FO-DICOM.Core/DicomItemComparer.cs
> +            return x.Tag == y.Tag;
Yes, much better, thanks!

2021-11-19 19:20 UTC, mrbean-bremen commented on FO-DICOM.Core/DicomItemComparer.cs
> +                var element2 = dataset2.ElementAt(i);
Tags are always ordered, otherwise it would be invalid DICOM, so I would consider that different (I have only once seen an example of some private tags in the wrong order, and that crashed dcmtk's storeSCP).

2021-11-19 19:22 UTC, mrbean-bremen commented on FO-DICOM.Core/DicomItemComparer.cs
> +                var element1 = dataset1.ElementAt(i);
Yes, there is definitely room for improvement here. As I wrote, I completely ignored performance here, as it is used only for a couple of tests, but in reality it could be used elsewhere.

2021-11-19 19:23 UTC, mrbean-bremen commented on FO-DICOM.Core/IO/NoSeekStreamByteSource.cs
> +    public class NoSeekStreamByteSource : IByteSource
Yes, better. As I wrote, I'm no good with names...

2021-11-19 19:23 UTC, mrbean-bremen commented on FO-DICOM.Core/IO/NoSeekStreamByteSource.cs
> +        /// <summary> Reader for buffer that accounts for Endianess. </summary>
I always get this one wrong.

2021-11-19 19:24 UTC, mrbean-bremen commented on FO-DICOM.Core/IO/NoSeekStreamByteSource.cs
> +                // TODO: log warning?
yes, I'm still not sure what is the correct way for logging here - I had the same problem with the encoding stuff

2021-11-19 19:25 UTC, mrbean-bremen commented on FO-DICOM.Core/IO/NoSeekStreamByteSource.cs
> +                    return bytesInBuffer.Concat(bytesInSource).ToArray();
Ok

2021-11-19 19:31 UTC, mrbean-bremen commented on FO-DICOM.Core/IO/NoSeekStreamByteSource.cs
> +            lock (_lock)
Actually this was a point I was not sure about at all - I used locking in the same places as `StreamByteSource`, but you are right, that would certainly not be enough to be thread safe. I have no idea if this is a use case here, maybe @gofal can shed some light here...

2021-11-19 19:41 UTC, mrbean-bremen commented on FO-DICOM.Core/DicomItemComparer.cs
> +                var element1 = dataset1.ElementAt(i);
I have been thinling about adding `Equals` in `DicomDataset`, but wasn't sure about the implications. I tried to not add anyting potentially breaking.

2021-11-19 20:15 UTC, mrbean-bremen commented on FO-DICOM.Core/IO/NoSeekStreamByteSource.cs
> +            if (_bufferState == BufferState.Read || _bufferState == BufferState.ReadWrite)
Actually I did this yesterday, this must have been be an outdated version.

2021-11-19 20:22 UTC, mrbean-bremen commented
> This might be the same issue I had with the invalid DICOM files. Fellow Oak DICOM definitely parses files differently 

I had another look, and this seems to be a problem with `MemoryMappedFile.CreateViewStream` which is used in the test, so not really a fo-dicom problem. And yes, fo-dicom is more forgiving in these cases, probably because it does not check the correct order of tags, so that for example a (0000,0000) tag does not generate an error. It would be nice to have at least a warning here, I think, and I think such tags shall be ignored instead of added to the dataset. Something for later, maybe...

2021-11-19 20:25 UTC, mrbean-bremen commented
I also had just the second time a test failing in CI (`GetByteRange_CompareWithInitializer_ExactMatch`) ecause of a missing temp file - not sure if something has changed here lately, or the test has always been shaky.

2021-11-21 17:24 UTC, mrbean-bremen commented on FO-DICOM.Core/IO/NoSeekStreamByteSource.cs
> +            lock (_lock)
For the time being I have removed the locks, assuming we don't need to be thread-safe here. If we need to be, this has to be revised. Also, I didn't understan why access to `_milestones` has to be locked (as is done in `StreamByteSource`, as there is no global state involved, as far as I can see.

2021-11-22 08:13 UTC, gofal commented
> 
> This might be the same issue I had with the invalid DICOM files. Fellow Oak DICOM definitely parses files differently from MicroDicom or dcmdump, because both these files reject / throw an error when I opened a file with gibberish at the end, while DicomFile.Open just worked. The parser seems to make a "best effort" in trying to make sense of things, and just throws the towel in the ring at some point. However, all successfully read tags are usable, so I guess it's not a bad feature. It does however make it harder to detect corrupt files.

This is due to the stragety: *Be as strickt as possible when creating data, but be as tollerant as possible when receiving data.* Agree that is is harder to detect corrupt files. Many, many issues have been solved the last years with kind of "fo-dicom does not render this file" - "yes, because it is courrupt" - "but the application XY also renders this image and now there are many images of that kind, so i have to render them somehow".

There is that gread DVT validation tool in java. fo-dicom could have such a validation method also when reading files, not only when writing.

2021-11-22 08:16 UTC, amoerie commented on FO-DICOM.Core/DicomItemComparer.cs
> +                var element2 = dataset2.ElementAt(i);
Good point, I completely forgot about that for a minute there. Carry on. 😁

2021-11-22 08:18 UTC, amoerie commented
> I also had just the second time a test failing in CI (`GetByteRange_CompareWithInitializer_ExactMatch`) because of a missing temp file - not sure if something has changed here lately, or the test has always been shaky.

Yeah I had a feeling the TempFile test was flaky and unrelated to my changes, but it's very hard to prove. I guess this proves my changes *were* unrelated because none of them are merged yet! :-)

2021-11-22 08:26 UTC, amoerie commented
> This is due to the stragety: _Be as strickt as possible when creating data, but be as tollerant as possible when receiving data._ Agree that is is harder to detect corrupt files. Many, many issues have been solved the last years with kind of "fo-dicom does not render this file" - "yes, because it is courrupt" - "but the application XY also renders this image and now there are many images of that kind, so i have to render them somehow".
> 
> There is that gread DVT validation tool in java. fo-dicom could have such a validation method also when reading files, not only when writing.

I think it's great that Fellow Oak DICOM can handle all kinds of corrupt files, but I did wish it would print a warning or provide a separate validator indeed so we can check whether files are perfectly valid and not corrupt. Perhaps something to put in the idea box. 🙂

2021-11-22 08:26 UTC, merged

2021-11-22 12:59 UTC, gofal commented on FO-DICOM.Core/IO/UnseekableStreamByteSource.cs
> +    public static class StreamByteSourceFactory
This should be in a separate class, but at least on in UnseekableStreamBytesource.cs
if there are some static extension methods classes that are only related to the actual class, then it would be ok to have them within the same file. But the StreamByteSourceFactory is a factory class that returns sometimes a UnseekableStreamByteSource, but most of the time a StreamByteSource. So it's not in the right place here

2021-11-22 13:03 UTC, mrbean-bremen commented on FO-DICOM.Core/IO/UnseekableStreamByteSource.cs
> +    public static class StreamByteSourceFactory
Ok, will change this in a new PR, as this has been already merged.

2021-11-22 13:07 UTC, amoerie commented on FO-DICOM.Core/IO/UnseekableStreamByteSource.cs
> +    public static class StreamByteSourceFactory
> This should be in a separate class, but at least on in UnseekableStreamBytesource.cs if there are some static extension methods classes that are only related to the actual class, then it would be ok to have them within the same file. But the StreamByteSourceFactory is a factory class that returns sometimes a UnseekableStreamByteSource, but most of the time a StreamByteSource. So it's not in the right place here

You're right, but this pattern exists in other places in fo-dicom too, such as EvenLengthBuffer.Create

I didn't know you were still reviewing this, since you already approved it, sorry for merging too quickly!

2021-11-22 13:38 UTC, gofal commented on FO-DICOM.Core/IO/UnseekableStreamByteSource.cs
> +    public static class StreamByteSourceFactory
sure, i approved it 13 days ago, but since then many changes have been done, so I did another review now. 
this is nothing important, just noticed it. The "evenlengthbuffer.create" is a static method in class EvenLengthBuffer and located in file EvenLengthBuffer.cs. so the policy to put classes into separate files with the filename to be the same as the classname is not broken here. The cases I am aware in fo-dicom are only those of static extension method classes.

2021-11-22 13:40 UTC, gofal commented on FO-DICOM.Core/IO/UnseekableStreamByteSource.cs
> +    public static class StreamByteSourceFactory
i am commiting that directly into dev now.

2021-11-22 14:59 UTC, gofal commented
> > I also had just the second time a test failing in CI (`GetByteRange_CompareWithInitializer_ExactMatch`) because of a missing temp file - not sure if something has changed here lately, or the test has always been shaky.
> 
> Yeah I had a feeling the TempFile test was flaky and unrelated to my changes, but it's very hard to prove. I guess this proves my changes _were_ unrelated because none of them are merged yet! :-)

went through github actions. first time this temp-test failed was on 10th november, so after the commit "optimize memory consumption when writing DICOM files" on 9th november. I will investigate this commit in more detail

2021-11-22 15:19 UTC, amoerie commented
> went through github actions. first time this temp-test failed was on 10th november, so after the commit "optimize memory consumption when writing DICOM files" on 9th november. I will investigate this commit in more detail

Ah that's actually a good point. In the past, we did _fs.Read(buffer) and now we do _fs.CopyTo instead.
There must be a subtle difference between the two that makes the OS think it's okay to delete the temporary file.

2021-11-22 17:30 UTC, gofal commented
I cannot find something that could be the reason for the failing tests. 
Also thought about timing thing, that the tempfilename was generated non-unique and therefore on thread cleanedup the file that was also used by another tread (better performance may cause such isses). 
Or about timing issues with other tests, where TemporaryFile.StoragePath, a static value pointing to themporary files storage, is changed. 
In the end I figured out, that the test fails with TempFilebuffer, wich is used nowhere in fo-dicom5, except in TempFileBufferTest. Don't know if it is critical. A DicomStoreSCP relies on Tempfile handling, because the received files are streamed into a tempfile instead of stored in memory (can be large datafiles).

2021-11-22 17:57 UTC, amoerie commented
I'm pretty sure the C-Store flow does not go through the TempFileBuffer, because that's handled by DicomService directly. If it's only used by tests, perhaps we can just remove the code plus the tests?