Enhance Association Request Timeout (1284)
fo-dicom/fo-dicom pull request #1285
Opened 2021-12-08 23:43 UTC by BobSter3000

Update associatonRequestTimesout state in  DicomClientAssociationState

Fixes # 1284.

#### Checklist
- [X] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [ ] I have updated API documentation
- [ ] I have included unit tests
- [X] I have updated the change log
- [X] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
- Updates DicomClient Association Request Timeout state so that the state transisitions to TransitionToCompletedWithErrorState instead of TransitionToCompletedState.
- Add new Exception for TransitionToCompletedWithErrorState
-

2021-12-09 08:57 UTC, amoerie commented
Looks like a unit test is failing now, in the v5-net-framework build.
Since the net-core-21 and net-core-31 builds are succeeding, we can assume this bug doesn't always occur but is circumstantial.

This is the exception:

```
[xUnit.net 00:00:16.80]     FellowOakDicom.Tests.Network.AsyncDicomCEchoProviderTests.OnCEchoRequestAsync_ShouldRespond [FAIL]
  Failed FellowOakDicom.Tests.Network.AsyncDicomCEchoProviderTests.OnCEchoRequestAsync_ShouldRespond [12 s]
  Error Message:
   FellowOakDicom.Network.DicomAssociationRequestTimedoutException : Association Request timed out waiting for response
  Stack Trace:
     at FellowOakDicom.Network.Client.States.DicomClientCompletedState.<GetNextStateAsync>d__8.MoveNext() in D:\a\fo-dicom\fo-dicom\FO-DICOM.Core\Network\Client\States\DicomClientCompletedState.cs:line 127
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FellowOakDicom.Network.Client.DicomClient.<Transition>d__91.MoveNext() in D:\a\fo-dicom\fo-dicom\FO-DICOM.Core\Network\Client\DicomClient.cs:line 267
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FellowOakDicom.Network.Client.States.DicomClientConnectState.<GetNextStateAsync>d__5.MoveNext() in D:\a\fo-dicom\fo-dicom\FO-DICOM.Core\Network\Client\States\DicomClientConnectState.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FellowOakDicom.Network.Client.DicomClient.<Transition>d__91.MoveNext() in D:\a\fo-dicom\fo-dicom\FO-DICOM.Core\Network\Client\DicomClient.cs:line 267
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FellowOakDicom.Network.Client.States.DicomClientIdleState.<SendAsync>d__5.MoveNext() in D:\a\fo-dicom\fo-dicom\FO-DICOM.Core\Network\Client\States\DicomClientIdleState.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FellowOakDicom.Network.Client.DicomClient.<SendAsync>d__110.MoveNext() in D:\a\fo-dicom\fo-dicom\FO-DICOM.Core\Network\Client\DicomClient.cs:line 377
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FellowOakDicom.Tests.Network.AsyncDicomCEchoProviderTests.<OnCEchoRequestAsync_ShouldRespond>d__2.MoveNext() in D:\a\fo-dicom\fo-dicom\Tests\FO-DICOM.Tests\Network\AsyncDicomCEchoProviderTests.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

There's a few things at play here:
- the default association request timeout is 5 seconds
- we are not guaranteed to have a very performant CI server
- even if we have a performant CI server, it can be busy with another test in parallel that is very demanding

Previously, if an association request times out, the DicomClient would cycle through its cleanup states and eventually retry.
You could argue this improves the stability of the DicomClient. 
On the other hand, if it keeps timing out, it's stuck in an endless loop, which is also not good.

I'm now starting to doubt whether this is an improvement. Wouldn't our efforts better be focused on adding an "escape hatch" if the association request keeps timing out? For example, we could expose a new event `DicomClient.AssociationRequestTimedOut`
This would allow consumers to count the number of times this happens and then set a CancellationTokenSource to canceled, which would cancel `SendAsync`. This is just one option.

What do you think @BobSter3000 ? I'm open to suggestions.

2021-12-09 09:40 UTC, gofal commented
Agree. Or a property MaxRetryCount, which is very common in many libraries.

2021-12-09 10:21 UTC, amoerie commented
I like the idea of a MaxRetryCount, but then we do need to think what should happen when a MaxRetryCount = 3 and a new request is added after attempt 2. Does the retry count reset or not? 
If the next attempt fails, is that then failure number 3 (for the already queued requests) or failure number 1 (for the newly added request)…

I think resetting the counter makes the most sense. Also, I believe that the number of people who add requests while already sending will be a minority.

2021-12-09 13:02 UTC, BobSter3000 commented
I lke the idea of the event and letting the consumer decide how to handle it with an event,  Just like the RequestTimed Event.  I will see what I can come up with.

2021-12-09 20:12 UTC, BobSter3000 commented
@amoerie First attempt at implemeting an event that fires when the Assoication Request times out.  There is also a max retry count for the association requests.   If the retry count exceeds the max retry count the exception is thrown.  I am not sure if this is OK or not.
Default Max Retry Count = 3.
Association Request sent
Association Request not responded within timeout Event Fired and Retry Count updated retry
Once Max Retry count is exceeded TransitionToCompletedWithErrorState with the timeout exception

2021-12-10 10:20 UTC, amoerie requested changes
The code changes look good, but I think we should add two missing unit tests:

1. One new test that verifies this new exception is thrown after 3 timeouts. 
2. One new test that verifies association requests are always tried 3 times. 

If you would like some assistance with writing the tests, please let me know. I can give pointers or help you set something up. If you want to take a stab at it, you can find a lot of scenarios in the DicomClientTests and DicomClientTimeoutTests.

2021-12-10 10:20 UTC, amoerie commented on FO-DICOM.Core/Network/Client/DicomClientOptions.cs
> +        /// The maximum number of Association Request Attempts after AssociationRequestTimeoutInMs expires
I would rephrase this to "The maximum number of times an association request will be sent before giving up (in the event of a timeout, the request will be retried),  use <see cref="AssociationRequestTimeoutInMs" /> to configure the timeout"

2021-12-10 10:20 UTC, amoerie commented on FO-DICOM.Core/Network/Client/States/DicomClientRequestAssociationState.cs
> +                    var exception = new DicomAssociationRequestTimedoutException();
I think you have to reset the AssociationRequestRetryCount here. Otherwise, in future SendAsync invocations, the request will not be retried.

2021-12-10 10:20 UTC, amoerie commented on FO-DICOM.Core/Network/Client/EventArguments/AssociationRequestTimedOutEventArgs.cs
> +        public int Timeout { get; }
Please either use a TimeSpan or rename the property to TimeoutInMs to make it explicit what the unit of time is.

2021-12-10 12:50 UTC, BobSter3000 commented
@amoerie I will get started on these changes.  Thank you.

2021-12-10 13:16 UTC, amoerie commented on FO-DICOM.Core/Network/Client/States/DicomClientRequestAssociationState.cs
> +                    var exception = new DicomAssociationRequestTimedoutException();
You will also have to reset this count if the association request does NOT timeout (accept or reject)

2021-12-10 18:08 UTC, BobSter3000 commented
@amoerie I am having a problem trying to setup the second unit test requested.
2. One new test that verifies association requests are always tried 3 times.
I just do not see a way to see when the assocication is being requested again.  Maybe one of the state changed events?
The other unit test covers the exception and verifies the retry count.

2021-12-10 20:13 UTC, amoerie commented
I can help you out with that but please allow me some time. Thanks for the effort so far!

2021-12-11 14:02 UTC, BobSter3000 commented
@amoerie Thanks again for all the help on this.

2021-12-14 05:18 UTC, amoerie commented
@BobSter3000 I added two tests that verify the counter is reset when an association is accepted or rejected. These confirm that, when a timeout occurs, the same DicomClient can be reused again and will again try 2 or 3 times to associate.

You might notice that I also made some changes in seemingly unrelated parts. One is that the DicomClientConnectState was erroneously catching exception from the transition to the association request state, which since this PR starts throwing the timeout exception. This was wrong, and I moved the TransitionToAssociationRequestState outside the try block. The effect of the original code was that the completed with error state was entered multiple times. This caught my eye in the logs, and is now fixed.

Furthermore, and this was really subtle, I could see that the DicomClient connection cleanup would complete before the listener actually stops. I traced this back to the usage of TaskFactory.StartNew, which doesn't support await lambdas that return a Task. The result was that the Listener always completed much too quickly, causing confusing timings in the DicomClient logs. The solution was extremely simple: use Task.Run instead of TaskFactory.StartNew. We have lost the ability now to pass the flag "LongRunning", which hints at the TaskScheduler that a new dedicated thread should be launched, while Task.Run will borrow a thread from the threadpool. However, after reading up on some of the internal heuristics of the ThreadPool, it will also spin up extra threads if it sees some borrowed threads are long running, so ultimately the result will be the same as far as I can tell.

Sorry for "hijacking" your pull request to include these fixes.

2021-12-14 08:02 UTC, amoerie approved these changes

2021-12-14 13:05 UTC, BobSter3000 commented
@amoerie I really do appreciate all the.  Thanks again!

2021-12-14 18:18 UTC, mrbean-bremen approved these changes
LGTM

2021-12-16 07:10 UTC, gofal approved these changes

2021-12-16 08:27 UTC, merged

2021-12-16 08:27 UTC, amoerie commented
Merged! 🎉

Thanks for contributing @BobSter3000 !