Added property to skip adding the default Implicit VR Little Endian transfer syntax for CStoreRequest
fo-dicom/fo-dicom pull request #1476
Opened 2022-11-24 09:42 UTC by bjorn-malmo

Fixes #1475.

#### Checklist
- [x] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [ ] I have updated API documentation
- [ ] I have included unit tests
- [x] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
-
-
-

2022-11-24 12:20 UTC, mrbean-bremen approved these changes
Not sure about a unit test here - it should check that no association is negociated if that flag is on and the receiver does not accept the transfer syntax, but I'm not sure how expansive this would be.

2022-11-25 10:37 UTC, gofal commented on ChangeLog.md
> +* Added property to skip adding the default Implicit VR Little Endian transfer syntax for CStoreRequest (#1475)
Its not a "default" or "fallback" transfersyntax, but is is a *mandatory* transfersyntax

2022-11-25 11:06 UTC, bjorn-malmo commented on ChangeLog.md
> +* Added property to skip adding the default Implicit VR Little Endian transfer syntax for CStoreRequest (#1475)
It is referred to as "Dicom Default transfer syntax" in PS3.5 10.1

2022-11-30 07:34 UTC, amoerie commented on ChangeLog.md
> +* Added property to skip adding the default Implicit VR Little Endian transfer syntax for CStoreRequest (#1475)
I am also under the impression that all DICOM entities *must* always present Implicit VR as an option during the association handshake. 

From https://dicom.nema.org/dicom/2013/output/chtml/part05/chapter_10.html (emphasis mine)

> 10.1 DICOM Default Transfer Syntax
> DICOM defines a default Transfer Syntax, the DICOM Implicit VR Little Endian Transfer Syntax (UID = "1.2.840.10008.1.2 "), which shall be supported by every conformant DICOM Implementation. This implies that:
> 
> _**If an Application Entity issues an A-ASSOCIATE request, it shall offer the DICOM Implicit VR Little Endian Transfer Syntax in at least one of the Presentation Contexts associated with each offered Abstract Syntax.**_
> 
> Note
> Offering Abstract Syntax (AS1) in two Presentation Contexts with Transfer Syntaxes (TS1) and (TS2) is not valid, but offering AS1-TS1, AS1-TS2 and AS1-TSD is valid because the DICOM Default Little Endian Transfer Syntax (TSD) is present in at least one of the Presentation Contexts that are based on Abstract Syntax (AS1).
> 
> If an Application Entity receives an A-ASSOCIATE indication corresponding to a request that follows the requirements specified in [Section 10.1](https://dicom.nema.org/dicom/2013/output/chtml/part05/chapter_10.html#sect_10.1) (a), every Presentation Context related to a given Abstract Syntax cannot be rejected in an A-ASSOCIATE response for the reason that none of the Transfer Syntaxes are supported.
> 
> Both of these requirements, (a) and (b), are waived when the Application Entity sending the pixel data has only access to the pixel data in lossy compressed form and a Transfer Syntax that uses a pixel data reference is not offered.
> 
> Requirement (b) to accept the default Transfer Syntax is waived if a Transfer Syntax that uses a pixel data reference is offered.
> 
> Note
> In other words, every sending AE is required to be able to convert any Data Set it is going to transmit into the default Transfer Syntax, regardless of the form in which it originally received or stored the Data Set, except in the single case of when it received it in a lossy compressed form. In that exceptional case, the sending AE is permitted to propose only the lossy compressed Transfer Syntax appropriate to the lossy form that was received.
> 
> In particular, this waiver does not apply to Data Sets received in a lossless compressed form, which means that any AE receiving a Data Set in a lossless compressed Transfer Syntax that needs to re-send the Data Set is required to be able to decompress it in order to support (at least) the default Transfer Syntax.
>

2022-11-30 07:35 UTC, amoerie requested changes
I believe this pull request should be rejected because Implicit VR is *not* optional, and pretending it is would be harmful.
See https://dicom.nema.org/dicom/2013/output/chtml/part05/chapter_10.html

2022-12-05 10:17 UTC, bjorn-malmo commented on ChangeLog.md
> +* Added property to skip adding the default Implicit VR Little Endian transfer syntax for CStoreRequest (#1475)
The standard is quite clear that it is perfectly permissible for an AE to propose only a lossy compressed transfer syntax under certain conditions. In the current standard, the wording is: 

**"In the case of lossy compressed Pixel Data, the sending AE is permitted to propose only the lossy compressed Transfer Syntax appropriate to the lossy form that was received." (PS3.5 Section 10.1)**

You have the same exception in the text cited above, even though the wording is different:

"Note
In other words, every sending AE is required to be able to convert any Data Set it is going to transmit into the default Transfer Syntax, regardless of the form in which it originally received or stored the Data Set, except in the single case of when it received it in a lossy compressed form. **In that exceptional case, the sending AE is permitted to propose only the lossy compressed Transfer Syntax** appropriate to the lossy form that was received."

I can't see the harm in having a property that would _allow_ the implementor to take use of this exception!

2022-12-05 12:18 UTC, mrbean-bremen commented
I agree with @bjorn-malmo here: there is clearly a use-case for this in the standard. I'm not sure if some check shall be added to ensure that this will only happen if a lossy transfer syntax is provided, or if it would be enough to make this clear in the documentation of the setting.

2022-12-05 15:39 UTC, amoerie commented on FO-DICOM.Core/Network/DicomCStoreRequest.cs
> +        public bool AddDefaultTransferSyntax { get; set; } = true;
I do wonder if this setting would make more sense at the DicomClient level, in ClientOptions

2022-12-05 15:44 UTC, amoerie commented
> I can't see the harm in having a property that would _allow_ the implementor to take use of this exception!

Very good point, I'm glad to learn something new. So we should support omitting the Implicit VR transfer syntax if - and only if - the original DICOM file is in a lossy format. 

If we do this, I think the setting should be more explicit and more strict though.
For example:

1) `bool DicomCStoreRequest.OmitDefaultTransferSyntaxInAssociationRequest`

This should throw an InvalidOperationException if the transfer syntax is not lossy, because that's the only scenario where this is allowed.

-or-

2) `bool DicomCStoreRequest.OmitDefaultTransferSyntaxInAssociationRequestIfPossible`

This would silently do nothing if the transfer syntax is not lossy. I prefer option 1.

I also wonder if we should explicitly use the name "ImplicitVrTransferSyntax" instead of "DefaultTransferSyntax", because not everyone knows that this is the default VR. So the setting would then become

3) `bool DicomCStoreRequest.OmitImplicitVrTransferSyntaxInAssociationRequest`

2022-12-06 08:41 UTC, bjorn-malmo commented
I don't have enough experience with the fo-dicom library yet to have any specific input, as long as it is possible to propose a single transfer syntax :)

2022-12-06 09:32 UTC, amoerie commented
> I don't have enough experience with the fo-dicom library yet to have any specific input, as long as it is possible to propose a single transfer syntax :)

Would you be willing to make the following changes to this PR:

- Rename DicomCStoreRequest.AddDefaultTransferSyntax to OmitImplicitVrTransferSyntaxInAssociationRequest
- Remove the default value "= true", false is the default value for a boolean in C# so this property would no longer need an explicit default value
- In DicomPresentationContextCollection, exclude the Implicit VR from the suggested transfer syntaxes like you are are doing in this PR, but throw an InvalidOperationException if the transfer syntax of the DicomFile is not lossy. I don't know how we can detect a lossy syntax, if necessary you can use a white list of known lossless syntaxes and just verify the transfer syntax is not one of those.

2022-12-07 08:44 UTC, bjorn-malmo commented
I've updated the PR in accordance with the above comment and also included unit tests for the new property.

2022-12-07 09:09 UTC, amoerie approved these changes
Looks perfect to me! Thanks for writing the tests too, they are very clean.

2022-12-07 09:10 UTC, amoerie commented
@gofal I will leave the actual merge up to you if you're alright with these changes. They look good to me!

2022-12-08 13:10 UTC, gofal approved these changes

2022-12-08 13:12 UTC, merged