Support for client certificates
fo-dicom/fo-dicom pull request #1514
Opened 2023-02-08 14:31 UTC by gofal

Fixes #1402 
Fixes #903 
Fixes #688 

#### Checklist
- [x] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [ ] I have updated API documentation
- [x] I have included unit tests
- [ ] I have updated the change log
- [x] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
- Add support for using X509 certificate(s) when authenticating over SSL as a client to a DICOM server
- Add ITlsInitiator and ITlsAcceptor interfaces that can be passed to client or server to completely customize certificate handling
- There are default implementations of those interfaces that will handle most of the use cases

#### Breaking changes proposed in this pull request:
- DicomServerFactory.Create does not allow certificatename as parameter any more, but requres a ITlsAcceptor, but there is an instance "new ZertificateTlsAcceptor(certificatename)" that will do the job.

2023-02-08 15:06 UTC, gofal commented
Please feel free to give feedback about the naming of the new interfaces and classes :-)

2023-02-08 18:29 UTC, mrbean-bremen commented
CC @mbesuden

2023-02-13 09:02 UTC, MBesuden commented on FO-DICOM.Core/Network/Tls/ZertificateTlsAcceptor.cs
> +    public class ZertificateTlsAcceptor : ITlsAcceptor
Probably a typo? Proposal: Rename to CertificateTlsAcceptor

2023-02-13 09:28 UTC, MBesuden approved these changes

2023-02-13 11:06 UTC, gofal commented on FO-DICOM.Core/Network/Tls/ZertificateTlsAcceptor.cs
> +    public class ZertificateTlsAcceptor : ITlsAcceptor
Sure, absolutely right. I had the german way of typing "certificate" in mind.

2023-02-15 13:07 UTC, MBesuden approved these changes

2023-02-28 14:48 UTC, amoerie commented on FO-DICOM.Core/Network/Tls/DefaultTlsInitiator.cs
> +            var authenticationSucceeded = Task.Run(() => ssl.AuthenticateAsClientAsync(remoteAddress, certificates, Protocols, CheckCertificateRevocation)).Wait(SslHandshakeTimeout);
It's unfortunate that this is not truly async, but uses the synchronous Wait API

2023-02-28 14:54 UTC, amoerie commented on FO-DICOM.Core/Network/Tls/CertificateTlsAcceptor.cs
> +    public class CertificateTlsAcceptor : ITlsAcceptor
Maybe this class should also be called DefaultTlsAcceptor?

2023-02-28 15:02 UTC, amoerie commented
Hi @gofal I'll reply here so we might have a discussion here about these changes. 
I am intrigued by your approach, but I have one strong gut feeling against this change, and that is that you are passing these ITlsAcceptor and ITlsInitiator instances around as parameters. This seems unnecessarily flexible? 
I think being able to override the default implementation using dependency injection is more than enough. This now complicates the API imho.

On the other hand, I agree with you that it's nicer to review pull requests when the refactoring and the new features are done in separate PRs. However, my refactoring was not done just for sport: the synchronous wait can introduce deadlocks, so my creation of DesktopNetworkStreamFactory was introduced to move it out of the DesktopNetworkStream constructor so it could be truly async.

2023-02-28 15:50 UTC, gofal commented on FO-DICOM.Core/Network/Tls/CertificateTlsAcceptor.cs
> +    public class CertificateTlsAcceptor : ITlsAcceptor
Agree, as I stated above, the naming is open for discussion.
I also thought of providing some Acceptors in fo-dicom by default like "DefaultAcceptor", which will accept every client, "CAAcceptor" that only accepts client certificates which have a certain CA in their chain. and so on.

2023-02-28 15:51 UTC, gofal commented on FO-DICOM.Core/Network/Tls/DefaultTlsInitiator.cs
> +            var authenticationSucceeded = Task.Run(() => ssl.AuthenticateAsClientAsync(remoteAddress, certificates, Protocols, CheckCertificateRevocation)).Wait(SslHandshakeTimeout);
Agree. This is because the DesktopNetworkStream is doing all its initialization within a construcot, where no real async is possible. This is something that I also noticed in the other PR. See the pending comment in NetwowkManager.cs
> this method calls CreateNetworkStreamImpl which is implemented as
protected internal override INetworkStream CreateNetworkStreamImpl(NetworkStreamCreationOptions options) =>  CreateNetworkStreamImplAsync(options, CancellationToken.None).GetAwaiter().GetResult();
>
>So this method's body is actually
Task.FromResult( CreateNetworkStreamImplasync(..).GetAwaiter().GetResult())
>
>such a sync over async construction was introduced with htat new DesktopNetworkSTreamFactory.

Restructuring the network layers and therefore introducing truly async is something that would not be scope of this PR

2023-02-28 16:01 UTC, gofal commented
Thanks for the feedback. 
The reason for passing the instances to the classes instead of a POC with some options flags is, that the handling of the TSL is separated. You should not have a gut feeling about this, because since Dependency Injection became a widely used pattern, we all are used to pass instances as parameters. That's how separation of concerns works best.

But I am open for discussion if the ITlsInitiator might be set as property of DicomClient. But this is already solved with the constructor overload where you can still pass "true" and then the instance from the DI-Container will be taken.
In case of TlsAcceptor in DicomServer, I think passing the services as parameter and not setting some properties fits bette to the DI pattern.

2023-02-28 16:25 UTC, gofal commented
The refactoring stuff is difficult enough. If it is then mixed with introducing some new features, then it gets really hard. So I am aware that you did not do it for the sports, but maybe a litte too rash?

For example when you write here that you introduced these factories to make real async to avoid deadlocks, then I have to tell you that you only moved this sync over async to another spot. The factories work fine, but still the main NetworkManger has the Method CreateNetworkStreamImplAsync, which then returns "Task.FromResult(CreateNetworkStreamImpl(options));" and your implementation there then calls the Awaiter: https://github.com/fo-dicom/fo-dicom/blob/4d0a6e95e85cf00d8ace5d6271443a3b41c3d4a2/FO-DICOM.Core/Network/DesktopNetworkManager.cs#L58

So you tried to avoid sync over async, but because of the complexity of your PR you seem to have missed this sync over async.
And maybe such things are woth some discussions and not adding it to some other feature as addon.

2023-02-28 19:34 UTC, amoerie commented
> Thanks for the feedback. 
> The reason for passing the instances to the classes instead of a POC with some options flags is, that the handling of the TSL is separated. You should not have a gut feeling about this, because since Dependency Injection became a widely used pattern, we all are used to pass instances as parameters. That's how separation of concerns works best.
> 
> But I am open for discussion if the ITlsInitiator might be set as property of DicomClient. But this is already solved with the constructor overload where you can still pass "true" and then the instance from the DI-Container will be taken.
> In case of TlsAcceptor in DicomServer, I think passing the services as parameter and not setting some properties fits bette to the DI pattern.

Thanks for the insights. I think I agree with your points and am willing to accept the parameter based implementation. 👍

2023-02-28 19:40 UTC, amoerie commented
> The refactoring stuff is difficult enough. If it is then mixed with introducing some new features, then it gets really hard. So I am aware that you did not do it for the sports, but maybe a litte too rash?
> 
> For example when you write here that you introduced these factories to make real async to avoid deadlocks, then I have to tell you that you only moved this sync over async to another spot. The factories work fine, but still the main NetworkManger has the Method CreateNetworkStreamImplAsync, which then returns "Task.FromResult(CreateNetworkStreamImpl(options));" and your implementation there then calls the Awaiter: https://github.com/fo-dicom/fo-dicom/blob/4d0a6e95e85cf00d8ace5d6271443a3b41c3d4a2/FO-DICOM.Core/Network/DesktopNetworkManager.cs#L58
> 
> So you tried to avoid sync over async, but because of the complexity of your PR you seem to have missed this sync over async.
> And maybe such things are woth some discussions and not adding it to some other feature as addon.

No that was not accidental, it was to retain backwards compatibility with the NetworkManager interface. I think you'll find that the normal, async methods are done properly all the way down (of course I am not perfect and can make mistakes)

I should also make a small correction: since we use .Wait with a timeout, there is actually no chance of a deadlock, but we are occupying a thread synchronously the whole time, which could be doing other things if we properly used async.

Ultimately, I am willing to accept and merge this pull request that just contains the new client certificates feature, but I still feel like some refactoring in this area should happen.

2023-03-02 20:54 UTC, amoerie commented
Looks like the certificate test is still failing in .NET Framework:

```
[xUnit.net 00:05:13.17]     FellowOakDicom.Tests.Network.Client.DicomClientTlsTest.SendAsync_WithClientCertificate_ShouldAuthenticate(requireMutualAuthentication: True) [FAIL]
  Failed FellowOakDicom.Tests.Network.Client.DicomClientTlsTest.SendAsync_WithClientCertificate_ShouldAuthenticate(requireMutualAuthentication: True) [15 s]
  Error Message:
   FellowOakDicom.Network.DicomAssociationRequestTimedOutException : The association request timed out 3 times, waiting 5000ms each time for the association response
  Stack Trace:
     at FellowOakDicom.Network.Client.DicomClient.<SendAsync>d__86.MoveNext() in D:\a\fo-dicom\fo-dicom\FO-DICOM.Core\Network\Client\DicomClient.cs:line 409
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at FellowOakDicom.Network.Client.DicomClient.<SendAsync>d__86.MoveNext() in D:\a\fo-dicom\fo-dicom\FO-DICOM.Core\Network\Client\DicomClient.cs:line 564
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FellowOakDicom.Tests.Network.Client.DicomClientTlsTest.<SendAsync_WithClientCertificate_ShouldAuthenticate>d__8.MoveNext() in D:\a\fo-dicom\fo-dicom\Tests\FO-DICOM.Tests\Network\Client\DicomClientTlsTest.cs:line 203
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  Standard Output Messages:
     XUnitDicomLogger   DEBUG  21:45:56.395 # 18               DicomClient : [IDLE] --> [CONNECTING]
     XUnitDicomLogger   DEBUG  21:45:56.395 # 77              IDicomServer : SSL policy errors: client certificate is missing
     XUnitDicomLogger   DEBUG  21:45:56.395 # 95               DicomClient : SSL Chain status [0]: UntrustedRoot A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.
 
     XUnitDicomLogger   DEBUG  21:45:56.395 # 22               DicomClient : [CONNECTING] --> [REQUESTING ASSOCIATION]
     XUnitDicomLogger   DEBUG  21:45:56.395 # 22               DicomClient : Sending association request from SCU to ANY-SCP
     XUnitDicomLogger    INFO  21:45:56.395 # 22               DicomClient : ANY-SCP -> Association request:
Calling AE Title:       SCU
Called AE Title:        ANY-SCP
Remote host:            
Remote port:            0
Implementation Class:   Implementation Class UID [1.3.6.1.4.1.30071.8]
Implementation Version: fo-dicom 5.0.3
Maximum PDU Length:     262144
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  1
  Presentation Context:  1 [Proposed]
       Abstract Syntax:  Verification SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
     XUnitDicomLogger   DEBUG  21:46:01.410 # 93               DicomClient : [REQUESTING ASSOCIATION] --> [CONNECTING]
     XUnitDicomLogger   DEBUG  21:46:01.410 # 98               DicomClient : An 'object disposed' exception occurred while listening to the network stream. This can happen when the connection is being closed. System.ObjectDisposedException: Cannot access a disposed object.
 Object name: 'SslStream'.
    at void System.Net.Security.SslState.CheckThrow(bool authSuccessCheck, bool shutdownCheck)
    at _SslStream System.Net.Security.SslState.get_SecureStream()
    at int System.Net.Security.SslStream.EndRead(IAsyncResult asyncResult)
    at void System.Threading.Tasks.TaskFactory<TResult>+FromAsyncTrimPromise<TInstance>.Complete(TInstance thisRef, Func<TInstance, IAsyncResult, TResult> endMethod, IAsyncResult asyncResult, bool requiresSynchronization)
    at async Task FellowOakDicom.Network.DicomService.ListenAndProcessPDUAsync() in D:/a/fo-dicom/fo-dicom/FO-DICOM.Core/Network/DicomService.cs:line 488
     XUnitDicomLogger    INFO  21:46:01.410 # 98               DicomClient : Connection closed
     XUnitDicomLogger   DEBUG  21:46:02.221 # 98              IDicomServer : SSL policy errors: client certificate is missing
     XUnitDicomLogger   DEBUG  21:46:02.221 # 95               DicomClient : SSL Chain status [0]: UntrustedRoot A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.
 
     XUnitDicomLogger   DEBUG  21:46:02.221 # 93               DicomClient : [CONNECTING] --> [REQUESTING ASSOCIATION]
     XUnitDicomLogger   DEBUG  21:46:02.221 # 93               DicomClient : Sending association request from SCU to ANY-SCP
     XUnitDicomLogger    INFO  21:46:02.221 # 93               DicomClient : ANY-SCP -> Association request:
Calling AE Title:       SCU
Called AE Title:        ANY-SCP
Remote host:            
Remote port:            0
Implementation Class:   Implementation Class UID [1.3.6.1.4.1.30071.8]
Implementation Version: fo-dicom 5.0.3
Maximum PDU Length:     2[621](https://github.com/fo-dicom/fo-dicom/actions/runs/4168065622/jobs/7214414756#step:4:622)44
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  1
  Presentation Context:  1 [Proposed]
       Abstract Syntax:  Verification SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
     XUnitDicomLogger   DEBUG  21:46:07.244 #  5               DicomClient : [REQUESTING ASSOCIATION] --> [CONNECTING]
     XUnitDicomLogger   DEBUG  21:46:07.244 # 77               DicomClient : An 'object disposed' exception occurred while listening to the network stream. This can happen when the connection is being closed. System.ObjectDisposedException: Cannot access a disposed object.
 Object name: 'SslStream'.
    at void System.Net.Security.SslState.CheckThrow(bool authSuccessCheck, bool shutdownCheck)
    at _SslStream System.Net.Security.SslState.get_SecureStream()
    at int System.Net.Security.SslStream.EndRead(IAsyncResult asyncResult)
    at void System.Threading.Tasks.TaskFactory<TResult>+FromAsyncTrimPromise<TInstance>.Complete(TInstance thisRef, Func<TInstance, IAsyncResult, TResult> endMethod, IAsyncResult asyncResult, bool requiresSynchronization)
    at async Task FellowOakDicom.Network.DicomService.ListenAndProcessPDUAsync() in D:/a/fo-dicom/fo-dicom/FO-DICOM.Core/Network/DicomService.cs:line 488
     XUnitDicomLogger    INFO  21:46:07.244 # 77               DicomClient : Connection closed
     XUnitDicomLogger   DEBUG  21:46:07.244 # 77              IDicomServer : SSL policy errors: client certificate is missing
     XUnitDicomLogger   DEBUG  21:46:07.244 # 95               DicomClient : SSL Chain status [0]: UntrustedRoot A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.
 
     XUnitDicomLogger   DEBUG  21:46:07.244 #  5               DicomClient : [CONNECTING] --> [REQUESTING ASSOCIATION]
     XUnitDicomLogger   DEBUG  21:46:07.244 #  5               DicomClient : Sending association request from SCU to ANY-SCP
     XUnitDicomLogger    INFO  21:46:07.244 #  5               DicomClient : ANY-SCP -> Association request:
Calling AE Title:       SCU
Called AE Title:        ANY-SCP
Remote host:            
Remote port:            0
Implementation Class: [...]

2023-03-20 23:33 UTC, gofal commented on FO-DICOM.Core/Network/Tls/CertificateTlsAcceptor.cs
> +    public class CertificateTlsAcceptor : ITlsAcceptor
is now renamed

2023-03-21 06:54 UTC, gofal commented
the tls handling in netframework is far more strict than in netcore. The test ran red on my machine reproducably. When debugging into I noticed, that the TlsAccpetor.CertificateValidationCallback had no x509Certificate passed (the parameter is null). So internaly the tcp server did not accept the certificate. 
Some research showed, that the certificate used by the client requires to have a Extendec Key Usage of "1.3.6.1.5.5.7.3.2, clientath". So I created a new Certificate with htat key usage values and the test was green on my machine. But sadly now on the build server it is still red and the server log says
```
     XUnitDicomLogger   DEBUG  23:47:23.002 # 17               DicomClient : [IDLE] --> [CONNECTING]
     XUnitDicomLogger   DEBUG  23:47:23.017 #110              IDicomServer : SSL policy errors: client certificate is missing
```
Now i assume some trusted CA issue or similar. Will do some further research

2023-05-04 07:22 UTC, amoerie requested changes
Reviewed this again. Looks very neat! I still have a few open questions, if you could take a look. :-)

2023-05-04 07:22 UTC, amoerie commented on Documentation/v5/usage/ssl.md
> +So you can easyly configure or set your server certificate on application startup by configuring the DI services. This is also usefull if you want go get some other methods from DI service provider w
nitpick: useful

2023-05-04 07:22 UTC, amoerie commented on Documentation/v5/usage/ssl.md
> +The DicomClient factory method `DicomClientFactory.Create` can take a instance of `ITlsAcceptor` as parameter. With that, your client can initiate an ssl connection to a DicomServer with the method
This should be `ITlsInitiator`

2023-05-04 07:22 UTC, amoerie commented on Documentation/v5/usage/ssl.md
> +fo-dicom comes with a default implementation of this interface, namely `DefaultTlsInitiator`. This implementation has some properties with that you can control the behavior. For example you can turn
Nitpick: This implementation has some properties to control the behavior

2023-05-04 07:22 UTC, amoerie commented on FO-DICOM.Core/Network/Client/DicomClientFactory.cs
> +        /// <param name="tlsInitiator">The handler to initialte TLS security, if null then to TLS is enabled.</param>
Nitpick: no TLS is enabled

2023-05-04 07:22 UTC, amoerie commented on FO-DICOM.Core/Network/Client/DicomClientFactory.cs
> +        /// <param name="tlsInitiator">The handler to initialte TLS security, if null then to TLS is enabled.</param>
Nitpick: then no TLS is enabled

2023-05-04 07:22 UTC, amoerie commented on FO-DICOM.Core/Network/Tls/DefaultTlsInitiator.cs
> +            var authenticationSucceeded = Task.Run(() => ssl.AuthenticateAsClientAsync(remoteAddress, certificates, Protocols, CheckCertificateRevocation)).Wait(SslHandshakeTimeout);
OK yeah this goes back to the discussion we had before. :-) Alright for this PR then!

2023-05-04 07:22 UTC, amoerie commented on FO-DICOM.Core/Network/Client/DicomClientFactory.cs
> +            _serviceProvider = serviceProvider;
Why don't you simply inject the ITlsInitiator instead of the IServiceProvider?

2023-05-04 07:22 UTC, amoerie commented on FO-DICOM.Core/Network/DicomServerFactory.cs
> +            tlsAcceptor ??= dicomServerScope.ServiceProvider.GetService<ITlsAcceptor>();
Why do you resolve the ITlsAcceptor from the newly created server scope instead of simply injecting an ITlsAcceptor into the DicomServerFactory?

2023-05-04 07:22 UTC, amoerie commented on FO-DICOM.Core/Network/Tls/DefaultTlsAcceptor.cs
> +                throw new DicomNetworkException("Client TLS authentication failed");
Nitpick: maybe we want to use the word "Mutual" in this error message to better guide people to the required fix.

2023-05-14 09:23 UTC, gofal commented on FO-DICOM.Core/Network/DicomServerFactory.cs
> +            tlsAcceptor ??= dicomServerScope.ServiceProvider.GetService<ITlsAcceptor>();
it's because on the one hand the api should be simple enough, that the server just gets the ITlsAcceptor from DI, so that it has to be configured only once on startup - I guess that will be the recommended default.
On the other hand I know of situations (in our applications) where you are running selveral DicomServer-Instances in one service. There I might have the need to configure different behavior (certificate). 
With that pattern the DicomServer can handle both cases.

2023-05-14 09:41 UTC, gofal commented on FO-DICOM.Core/Network/Client/DicomClientFactory.cs
> +            _serviceProvider = serviceProvider;
because this is the factory, and the implementation is used within a concrete client.
If I would get the ITlsInitiator here directly into this singleton factory, than also the ITlsInitiator would be such an singleton - becasue it would be exactly one instance for all clients.
But I do not know, if someone has an implementation that needs to be scoped (because of some database-action to verify the certificate or whatever). 
Anyway, if I would have taken the ITlsInitiator here, then this would be a unnecessary lifetime-restriction to the implementation. It is for the similar reason, why this method takes an LoggerFactory and not the conrete ILogger, or the DicomclientconnectionFactory, and not the concrete DicomClientconnection.

2023-05-14 09:43 UTC, gofal commented on Documentation/v5/usage/ssl.md
> +So you can easyly configure or set your server certificate on application startup by configuring the DI services. This is also usefull if you want go get some other methods from DI service provider w
thanks. All my english texts and documentations really need some extra review :-)

2023-05-15 07:16 UTC, amoerie commented on FO-DICOM.Core/Network/Client/DicomClientFactory.cs
> +            _serviceProvider = serviceProvider;
Scoped is not an option here I think. DicomClientFactory itself is a singleton, so that means the injected IServiceProvider can only be the root service provider, unless I'm mistaken.
The only remaining option is transient, where each ITlsInitiator is a new instance. 
The only way I can imagine this supporting scopes is if you override the DicomClientFactory registration in DI to use a scoped lifetime.

2023-05-15 07:19 UTC, amoerie commented on FO-DICOM.Core/Network/DicomServerFactory.cs
> +            tlsAcceptor ??= dicomServerScope.ServiceProvider.GetService<ITlsAcceptor>();
Oh I did not ask the question clearly enough, my question was not about supporting both a parameter and DI, it was about the fact that you use `dicomServerScope.ServiceProvider.GetService<ITlsAcceptor>()` instead of simply injecting an `ITlsAcceptor` in the constructor of `DicomServerFactory`. I guess my question here is mostly the same discussion/question as in `DicomClientFactory`

2023-05-15 07:51 UTC, gofal commented on FO-DICOM.Core/Network/Client/DicomClientFactory.cs
> +            _serviceProvider = serviceProvider;
sure, I mixed up the wordings of scoped and transient. The point I wanted to say, I did not want to force a static behavior. Having some transient instances is not a bad idea per se, it very much depends on the concrete implementation. 
fo-dicom takes the instance from DI on demand. So it's up to the user, to register the implementation as Singleton (propably in most of the implementations) or as Transient (could be possible). 
But what is the drawback that you see here?

2023-05-15 07:53 UTC, gofal commented on FO-DICOM.Core/Network/DicomServerFactory.cs
> +            tlsAcceptor ??= dicomServerScope.ServiceProvider.GetService<ITlsAcceptor>();
yes, it's roughly the same as above. The factory itself does not need the implementation. so the factory should not request the implementation once and hold forever. The factory should get the implementation on demand. So the lifetime is up to the user instead of forced to singleton.

2023-05-15 07:58 UTC, amoerie commented on FO-DICOM.Core/Network/Client/DicomClientFactory.cs
> +            _serviceProvider = serviceProvider;
> Having some transient instances is not a bad idea per se, it very much depends on the concrete implementation.

You're probably right. Disregard! Consumers can still use singleton if they want, and transient if they need.
My only remaining "concern" is that this requires a service lookup every time, but that is easily avoidable by using the other overload that takes an ITlsAcceptor.  
So, all good!

2023-05-15 07:58 UTC, amoerie approved these changes

2023-05-15 13:31 UTC, merged

2023-05-21 17:28 UTC, MrBean2016 commented
Great work, really a feature long-awaited