Added User Identity Negotiation support (#1110)
fo-dicom/fo-dicom pull request #1546
Opened 2023-04-22 06:09 UTC by PantelisGeorgiadis

Fixes #1110.

#### Checklist
- [X] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [ ] I have updated API documentation
- [X] I have included unit tests
- [X] I have updated the change log
- [X] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
- Added [User Identity Negotiation](https://dicom.nema.org/medical/dicom/current/output/chtml/part07/sect_D.3.3.7.html) support.

2023-04-30 07:07 UTC, PantelisGeorgiadis commented
@amoerie, @mrbean-bremen, @gofal, any feedback on this?

2023-05-01 15:58 UTC, mrbean-bremen approved these changes
Thank you - as far as I can tell, this all looks good, though I had to read up on user identity negotiation, not being aware of it before.

2023-05-01 15:58 UTC, mrbean-bremen commented on README.md
> +client.NegotiateUserIdentity(new DicomUserIdentityNegotiation
Maybe add a comment that this is optional, as this is example code in the Readme

2023-05-02 05:42 UTC, gofal commented
Thank you very much!
The same is true for me. I knew there was this kind of handshake, but I had no ideas about the details and I am currently reading into this topic.

Have you tested the code with other DICOM implementions?

2023-05-02 09:54 UTC, PantelisGeorgiadis commented on README.md
> +client.NegotiateUserIdentity(new DicomUserIdentityNegotiation
Thank you @mrbean-bremen! A comment has been added to denote that this is an optional operation.

2023-05-02 10:04 UTC, PantelisGeorgiadis commented
Thank you @mrbean-bremen and @gofal for your comments!
Indeed, User Identity Negotiation is not a widely known feature but it is a nice one to have! DCMTK and DCM4CHEE already supports it.

@gofal, I have tested this branch against DCMTK as client and server!

2023-05-02 10:31 UTC, gofal commented
When transfering data via a public network connection, I used to think that we have to skip old DICOM DIMSE because of security and we have to switch to proprietary protocols or to move to DICOMWeb. 
But with the better ssl support now and this User Identity Negotiation having JWT Token, I start thinking that there should be absolutely no problem to use pure old DICOM protocol in a very secure way, even over internet.

2023-05-02 10:55 UTC, PantelisGeorgiadis commented
@gofal, that's exactly what drew my attention to this feature!

2023-05-04 07:03 UTC, amoerie requested changes
Thanks for this contribution! Sorry it took me a while to review it, but I wanted to take my time and do it properly, so I had to wait for an opportunity to do so.
I also had to read up on the standard about this, and it's nice to know these things are possible. 

As for the code itself, all in all it looks like very solid work! I made a bunch of nitpicky comments, please don't take them the wrong way. Also feel free to argue if you disagree with any of them. :-)

2023-05-04 07:03 UTC, amoerie commented on FO-DICOM.Core/Network/DicomUserIdentityNegotiation.cs
> +        public DicomUserIdentityType UserIdentityType { get; set; } = DicomUserIdentityType.Username;
Is this a safe default? Wouldn't it be better to have this nullable and require people to make a choice?

2023-05-04 07:03 UTC, amoerie commented on FO-DICOM.Core/Network/DicomUserIdentityNegotiation.cs
> +        public String PrimaryField { get; set; } = String.Empty;
Nitpick: lowercase "string" instead of "String"

2023-05-04 07:03 UTC, amoerie commented on FO-DICOM.Core/Network/DicomUserIdentityNegotiation.cs
> +        public String PrimaryField { get; set; } = String.Empty;
Also here, I'd prefer to default to null instead of an empty string, unless the DICOM specification specifically requires  this. 
I believe that this is how it's also done everywhere else in fo-dicom.

2023-05-04 07:03 UTC, amoerie commented on FO-DICOM.Core/Network/DicomUserIdentityNegotiation.cs
> +        public String SecondaryField { get; set; } = String.Empty;
Same comments as PrimaryField

2023-05-04 07:03 UTC, amoerie commented on FO-DICOM.Core/Network/DicomUserIdentityNegotiation.cs
> +        public String ServerResponse { get; set; } = String.Empty;
Same comments as PrimaryField

2023-05-04 07:03 UTC, amoerie commented on FO-DICOM.Core/Network/Client/DicomClient.cs
> +        public void NegotiateUserIdentity(DicomUserIdentityNegotiation userIdentity) => UserIdentityNegotiation = userIdentity;
Do we want validation here? 
For example, the standard says that SecondaryField should only be present when the Type is 2 (username + pw)

2023-05-04 07:03 UTC, amoerie commented on FO-DICOM.Core/Network/PDU.cs
> +                pdu.Write("User Identity Secondary Field", _assoc.UserIdentityNegotiation.SecondaryField);
Is it okay to always write the secondary field here? 

From https://dicom.nema.org/medical/dicom/current/output/chtml/part07/sect_D.3.3.7.html 

> This field shall be present only if User-Identity-Type has the value 2. It shall contain the Passcode value.

2023-05-04 07:03 UTC, amoerie commented on Tests/FO-DICOM.Tests/Network/DicomUserIdentityNegotiationTest.cs
> +                    await association.ReleaseAsync(CancellationToken.None);
Nitpick: it makes more sense to release the association after it was successfully opened, so within the try block.
Furthermore, if ReleaseAsync would time out and throw an exception, the association is never disposed. 

In fact, since you don't use the association afterwards, I think this can be reduced to:

```csharp
try
{
    using var association = await connection.OpenAssociationAsync(openAssociationRequest, CancellationToken.None);
    await association.ReleaseAsync(CancellationToken.None);
}
catch (DicomAssociationRejectedException e)
{
    exception = e;
}
```

2023-05-04 07:03 UTC, amoerie commented on Tests/FO-DICOM.Tests/Network/DicomUserIdentityNegotiationTest.cs
> +                    Assert.NotNull(args.Association);
Nitpick: if the AssociationAccepted callback is never invoked, these assertions do not run. It's not inherently wrong, but I typically prefer to capture data from callbacks in local variables and then run assertions at the end of the test.

2023-05-04 07:03 UTC, amoerie commented on Tests/FO-DICOM.Tests/Network/DicomUserIdentityNegotiationTest.cs
> +                if (association != null)
Same nitpick as before

2023-05-04 07:03 UTC, amoerie commented on Tests/FO-DICOM.Tests/Network/DicomUserIdentityNegotiationTest.cs
> +                    association = args.Association;
Ah, and here you do the capturing as described before. :-)

2023-05-04 07:03 UTC, amoerie commented on Tests/FO-DICOM.Tests/Network/DicomUserIdentityNegotiationTest.cs
> +                if (association != null)
Same association cleanup nitpick as before

2023-05-04 07:03 UTC, amoerie commented on Tests/FO-DICOM.Tests/Network/DicomUserIdentityNegotiationTest.cs
> +                if (association != null)
Same nitpick :-)

2023-05-04 07:03 UTC, amoerie commented on Tests/FO-DICOM.Tests/Network/DicomUserIdentityNegotiationTest.cs
> +                if (association != null)
Same association nitpick cleanup as before. :-) I'll stop now, if there are future occurrences of this same pattern I presume you know where to find them.

2023-05-04 07:03 UTC, amoerie commented on Tests/FO-DICOM.Tests/Network/DicomUserIdentityNegotiationTest.cs
> +            public static readonly String KerberosServiceTicket = "KERBEROS_SERVICE_TICKET";
Any chance we can replace these with actual real-life like examples? We might discover possible length or character encoding issues that way.

ChatGPT gave me a few samples. I know nothing about Kerberos Service Tickets, but I do know SAML assertions and JWT, and those look okay.

Kerberos Service Ticket
```
Ticket:
Client Name: alice@EXAMPLE.COM
Server Name: host/server.example.com@EXAMPLE.COM
Ticket Encryption Type: aes256-cts-hmac-sha1-96
Ticket Flags: renewable, forwardable
Ticket Start Time: 2023-05-04T09:00:00Z
Ticket End Time: 2023-05-04T18:00:00Z
Ticket Authenticator:
Authenticator Encryption Type: aes256-cts-hmac-sha1-96
Authenticator Timestamp: 2023-05-04T10:00:00Z
````

SAML assertion
```xml
<saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="_3a4d46b3c4a7a90415adfa2f4f4a4a9b" IssueInstant="2023-05-04T10:00:00Z" Version="2.0">
  <saml:Issuer>https://idp.example.com/metadata</saml:Issuer>
  <saml:Subject>
    <saml:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified">alice@example.com</saml:NameID>
    <saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
      <saml:SubjectConfirmationData NotOnOrAfter="2023-05-04T10:30:00Z"/>
    </saml:SubjectConfirmation>
  </saml:Subject>
  <saml:Conditions NotBefore="2023-05-04T09:00:00Z" NotOnOrAfter="2023-05-04T18:00:00Z">
    <saml:AudienceRestriction>
      <saml:Audience>https://sp.example.com/metadata</saml:Audience>
    </saml:AudienceRestriction>
  </saml:Conditions>
  <saml:AuthnStatement AuthnInstant="2023-05-04T10:00:00Z">
    <saml:AuthnContext>
      <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml:AuthnContextClassRef>
    </saml:AuthnContext>
  </saml:AuthnStatement>
</saml:Assertion>
```

JWT Token
```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
```

2023-05-06 08:00 UTC, PantelisGeorgiadis commented
> Thanks for this contribution! Sorry it took me a while to review it, but I wanted to take my time and do it properly, so I had to wait for an opportunity to do so. I also had to read up on the standard about this, and it's nice to know these things are possible.
> 
> As for the code itself, all in all it looks like very solid work! I made a bunch of nitpicky comments, please don't take them the wrong way. Also feel free to argue if you disagree with any of them. :-)
> 
> P.S. Sooo Github does not add my comments in the order that I created them. If you see something like "same as before", then there is another comment already addressing a similar issue somewhere else. ;-)

Thank you @amoerie for your review!
Regarding "I made a bunch of nitpicky comments, please don't take them the wrong way"... What wrong way? This is a collective effort to make this library as usefull and robust as possible, there's no "wrong way"!
Thank you for your comments! As you will discover, I followed all your suggestions!

2023-05-06 08:00 UTC, PantelisGeorgiadis commented on FO-DICOM.Core/Network/DicomUserIdentityNegotiation.cs
> +        public DicomUserIdentityType UserIdentityType { get; set; } = DicomUserIdentityType.Username;
Thank you @amoerie! No, it is not... it is now switched to a nullable property.

2023-05-06 08:01 UTC, PantelisGeorgiadis commented on FO-DICOM.Core/Network/DicomUserIdentityNegotiation.cs
> +        public String PrimaryField { get; set; } = String.Empty;
Thank you @amoerie! `String` was changed to `string`.

2023-05-06 08:01 UTC, PantelisGeorgiadis commented on FO-DICOM.Core/Network/DicomUserIdentityNegotiation.cs
> +        public String SecondaryField { get; set; } = String.Empty;
Thank you @amoerie! `String` was changed to `string`.

2023-05-06 08:01 UTC, PantelisGeorgiadis commented on FO-DICOM.Core/Network/DicomUserIdentityNegotiation.cs
> +        public String ServerResponse { get; set; } = String.Empty;
Thank you @amoerie! `String` was changed to `string`.

2023-05-06 08:01 UTC, PantelisGeorgiadis commented on FO-DICOM.Core/Network/DicomUserIdentityNegotiation.cs
> +        public String PrimaryField { get; set; } = String.Empty;
Thank you @amoerie! The DICOM specification doesn't specifically require an empty string and, therefore, it is now defaulting to null.

2023-05-06 08:02 UTC, PantelisGeorgiadis commented on FO-DICOM.Core/Network/Client/DicomClient.cs
> +        public void NegotiateUserIdentity(DicomUserIdentityNegotiation userIdentity) => UserIdentityNegotiation = userIdentity;
Thank you @amoerie! A validation method was added in `DicomUserIdentityNegotiation` class (and unit tested). The user identity type and the secondary field are validated and the respected exceptions are thrown. This validation was applied in `NegotiateUserIdentity` and `OpenAssociationAsync` functions.

2023-05-06 08:03 UTC, PantelisGeorgiadis commented on FO-DICOM.Core/Network/PDU.cs
> +                pdu.Write("User Identity Secondary Field", _assoc.UserIdentityNegotiation.SecondaryField);
Thank you @amoerie! Now that validation is in-place, the secondary field won't be written, unless it is necessary (otherwise it is a zero-length write). In any case, the secondary field length should be written (even denoting zero-length secondary field value).

2023-05-06 08:03 UTC, PantelisGeorgiadis commented on Tests/FO-DICOM.Tests/Network/DicomUserIdentityNegotiationTest.cs
> +                    await association.ReleaseAsync(CancellationToken.None);
Thank you @amoerie! I followed the suggested pattern in all cases!

2023-05-06 08:03 UTC, PantelisGeorgiadis commented on Tests/FO-DICOM.Tests/Network/DicomUserIdentityNegotiationTest.cs
> +                    Assert.NotNull(args.Association);
Thank you @amoerie! As a matter of fact, the `AssociationAccepted` callback will never be invoked, since this test is testing for rejection! Therefore, the whole callback was removed.

2023-05-06 08:03 UTC, PantelisGeorgiadis commented on Tests/FO-DICOM.Tests/Network/DicomUserIdentityNegotiationTest.cs
> +                if (association != null)
Thank you @amoerie! I followed the suggested pattern in all cases!

2023-05-06 08:04 UTC, PantelisGeorgiadis commented on Tests/FO-DICOM.Tests/Network/DicomUserIdentityNegotiationTest.cs
> +                    association = args.Association;
Thank you @amoerie! Right!

2023-05-06 08:04 UTC, PantelisGeorgiadis commented on Tests/FO-DICOM.Tests/Network/DicomUserIdentityNegotiationTest.cs
> +                if (association != null)
Thank you @amoerie! I followed the suggested pattern in all cases!

2023-05-06 08:04 UTC, PantelisGeorgiadis commented on Tests/FO-DICOM.Tests/Network/DicomUserIdentityNegotiationTest.cs
> +                if (association != null)
Thank you @amoerie! I followed the suggested pattern in all cases!

2023-05-06 08:04 UTC, PantelisGeorgiadis commented on Tests/FO-DICOM.Tests/Network/DicomUserIdentityNegotiationTest.cs
> +                if (association != null)
Thank you @amoerie! I followed the suggested pattern in all cases!

2023-05-06 08:04 UTC, PantelisGeorgiadis commented on Tests/FO-DICOM.Tests/Network/DicomUserIdentityNegotiationTest.cs
> +            public static readonly String KerberosServiceTicket = "KERBEROS_SERVICE_TICKET";
Thank you @amoerie! I replaced the initial dummy short strings with "real" examples I found over the internet (your suggestions helped!). I couldn't find a Kerberos server response though... :-(

2023-05-06 12:16 UTC, amoerie commented
> Thank you @amoerie for your review! Regarding "I made a bunch of nitpicky comments, please don't take them the wrong way"... What wrong way? This is a collective effort to make this library as usefull and robust as possible, there's no "wrong way"! Thank you for your comments! As you will discover, I followed all your suggestions!

Super, thanks for going the extra mile!!

2023-05-06 12:16 UTC, amoerie approved these changes

2023-05-10 08:23 UTC, amoerie commented
> I start thinking that there should be absolutely no problem to use pure old DICOM protocol in a very secure way, even over internet.

We have been doing this for years already, works very well! 👌(With TLS certificate support in our fork)

2023-05-14 10:48 UTC, gofal commented
I've got a question regarding the role of `DicomUserIdentityNegotionation.PositiveResponseRequested`.
As far as I understand, if this is false, then the client just sends some username, that the server can use for logging etc, but as long as the server accepts the association, the client just continues sending requests.
But if this is set to true, then the client requests some positive negotiation. In Case the server does not support UserIdentityneogitation, the server just ignores this request subitem. But in that case, the client should *not* send requests to the server, isn't it?
in other words, what would be the difference if `dicomuserIdentityneogiation.PositiveResponseRequested` was set to `true` or to `false`?. In current implementation there is no difference.
In case of AdvancedDicomClient, after the `OpenAssociationAsync` call you can check the response of the Server if there is some UseridentityNeogiation subitem.
But in case of using the `DicomClient`, when adding some UserIdentityNegotiation with PositiveResponseRequested set to true, and the server does accept the Association but not return some response subitem (which means: the server does not implement this feature), shoudn't then the client stop sending and close the assication and then throw an DicomAssociationNegotiationFailedException (similar like an DicomAssociationRejectedException)?

But if I understood the DICOM standard wrong, and this field PositivieResponseRequested does not change any behavior but is always expected to be present and have the value 1, then the property in `DicomUserIdentityNegotionation.PositiveResponseRequested` should also be initialized to `true`, and in all the samples and unittests it should not be set explicitly. Or this property could be removed at all?

2023-05-14 13:15 UTC, PantelisGeorgiadis commented
That is a good question @gofal! I’ve put some thought into that, while implementing the feature. I ended up believing that the evaluation of the user identity negotiation (and subsequently of the `PositiveResponseRequested` value), should be handled by the implementing application and that the related logic, should not be included in the library. The library should just provide the information and the implementing application should decide what to do, based on its requirements.

Both SCU (using the OpenAssociationAsync’s returned value or DicomClient’s `AssociationAccepted` event – if the server doesn’t support the related sub-item) and SCP have access to the negotiated association object, that includes the UserIdentityNegotiation information. Both parties can evaluate the existence of the information, the `PositiveResponseRequested`, the primary/secondary fields and the server response and decide whether to proceed or stop.

I see your point and, of course, all the above are just my thoughts and I may be misinterpreting what the protocol suggests. In any case, I’m more than willing to hear and implement your suggestions.

2023-05-14 13:26 UTC, gofal commented
Sure, agree. I also try to not include too much application logic into this library. The goal is, to enforce the DICOM-standard. everything else should be handled in the application. So if the handling of the client depending on some properties is described in Standard, then fo-dicom also should care about it. Thant's why I was asking if I missed something in the DICOM standard regarding this property.

Then the only issue is: if we agree, that it's the applications resonsibility to check this property, then we have to add some entrypoint in DicomClient, where the user has the chance to check it. Currently in dicomclient the user can set the UserIdentityNegotation object, but then everything runs through. 
So either fo-dicom can handle this case (if it is clear enough, *how* to handle such cases), or there should be some kind of Callback or event, or property where the user can inject and decide how to go in in case the server does not handle the UserIdentityNegotiation properly

2023-05-14 14:15 UTC, PantelisGeorgiadis commented
Glad that you agree with my perspective! 

If you think that `DicomClient`’s `AssociationAccepted` event is not the right place to evaluate the returned user identity information (I demonstrate that in the unit tests) and take the proper course of action, then we can dive deeper and throw something like an `UserIndentityNegotiationFailedException`. We could evaluate the `PositiveResponseRequested` and the `ServerResponse` values in `AdvancedDicomClientConnection`’s `DicomAssociationAcceptedEvent` event and throw the exception accordingly. This could be caught in `DicomClient` and invoke a `UserIndentityNegotiationFailed` event. In this way we could cover both clients. 

Thoughts?

2023-05-14 16:05 UTC, gofal commented
With the AdvancedDicomclient you are completely fine, because there you can check the Association after the OpenAssociation method and before sending data.

But the DicomClient is the "simple API" for not so experienced DICOM-developers. There the AssociationAccepted Event is not enugh, because you receive an event, but the user cannot take any further actions. From within that handler you cannot cancel the sending of data properly. At this moment the enqueued Requests are already sent in background, the event is rather something informative to the user.

So in DicomClient.SendAsync after the Association was Accepted, pretty close to the spot where the AssociationAccepted event is invoked, there could be some validation of the proper UserIdentityNegotation response from the server and there
- some exception could be thrown
- some event with a .Handled or .Cancel property could be fired where the usercode then can set this propery and depending on that the DicomClient immediatelly closes the Association  properly without exceptions.

2023-05-15 08:11 UTC, amoerie commented
I like this sentence from the standard (https://dicom.nema.org/medical/dicom/current/output/chtml/part07/sect_D.3.3.7.html)

> The association requestor can then decide whether to proceed.

We might be able to have super simple support for this by simply adding a property to DicomClient that could be called "RequireUserIdentification" (please suggest a better name) that is true by default. 
This property has no effect if no user identity negotiation is configured.
If user identity negotation is used, and the property is true, it stops processing and throws a DicomNetworkException.
Otherwise, it logs a warning.

As for the advanced DICOM client, I would do nothing. It is up to advanced users to inspect the User Identity Negotiation and decide what to do.

2023-05-15 08:57 UTC, PantelisGeorgiadis commented
Agree @amoerie and will implement ASAP!

2023-05-15 08:59 UTC, amoerie commented
> Agree @amoerie and will implement ASAP!

I applaud the enthusiasm but you might want to wait and see if @gofal also finds this proposal acceptable :-)

2023-05-15 09:04 UTC, PantelisGeorgiadis commented
Ha ha ha! Definitely agree! @gofal, what do you think?

2023-05-15 09:18 UTC, gofal commented
😄  agree, this was also one of the suggested possibilities I mentioned earlier, so I am fine with it. Many thanks for implementing it!

2023-05-15 13:56 UTC, PantelisGeorgiadis commented
@amoerie, @gofal, based on your feedback, I added `RequireSuccessfulUserIdentityNegotiation` flag to `DicomClient`. When this is true and the `DicomUserIdentityNegotiation` is populated, the respected acknowledged object is evaluated and an exception is thrown, if necessary.

2023-05-15 14:03 UTC, gofal approved these changes
Many thanks!

2023-05-15 14:53 UTC, amoerie approved these changes

2023-05-15 17:38 UTC, merged

2023-05-15 17:42 UTC, PantelisGeorgiadis commented
Thank you guys!