Upgrade fo-dicom.Imaging.Desktop: support net6.0 and net7.0 in addition to net462 (#1318)
fo-dicom/fo-dicom pull request #1601
Opened 2023-05-26 17:42 UTC by timothylcooke

Fixes #1318 .

#### Checklist
- [X] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [ ] I have updated API documentation
- [X] I have included unit tests
- [ ] I have updated the change log
- [ ] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
- Upgrade FO-DICOM.Imaging.Desktop.csproj to sdk-style project.
- Add support for net6.0-windows and net7.0-windows for fo-dicom.Imaging.Desktop Nuget package

2023-05-26 17:44 UTC, timothylcooke commented
This slightly changes the nuspec file and dll properties shown in Windows Explorer.

Presumably you will want to remove `<Company>HP Inc.</Company>` from the csproj file. I added this only because of the `AssemblyCompanyAttribute`.

2023-05-26 17:47 UTC, timothylcooke commented
It didn't feel necessary to update the change log, documentation, or contributors files since the changes were so minor.

2023-05-28 09:24 UTC, gofal commented on Platform/FO-DICOM.Imaging.Desktop/FO-DICOM.Imaging.Desktop.csproj
> +    <Company>HP Inc.</Company>
Oh, yes, I think the "HP Inc" should not be here 😆

2023-05-30 17:58 UTC, timothylcooke commented on Platform/FO-DICOM.Imaging.Desktop/FO-DICOM.Imaging.Desktop.csproj
> +    <Company>HP Inc.</Company>
@gofal I removed the `<Company>HP Inc.</Company>` tag. Anything else I can do to help push this along? I can rebase and make it a single commit if you want.

2023-05-30 19:07 UTC, gofal commented on Platform/FO-DICOM.Imaging.Desktop/FO-DICOM.Imaging.Desktop.csproj
> +    <Company>HP Inc.</Company>
oh no, everything else looks fine to me. We usualy leave Pull Requests open for some time, so that contributors, who are not able to check the repository on a daily basis, do have the chance to add some thoughts or comments.

2023-05-30 19:12 UTC, mrbean-bremen approved these changes
Looks good to me, too!

2023-05-31 04:04 UTC, timothylcooke commented on Platform/FO-DICOM.Imaging.Desktop/FO-DICOM.Imaging.Desktop.csproj
> +    <Company>HP Inc.</Company>
Sounds good. I hope I'm not coming off as pushy. Frankly, I'm in no hurry to get this merged. Just trying to be helpful.

2023-05-31 18:50 UTC, timothylcooke commented
Bumped version number to match fo-dicom:development; removed duplicate AssemblyTitle tag.

2023-06-02 14:12 UTC, amoerie commented on Platform/FO-DICOM.Imaging.Desktop/FO-DICOM.Imaging.Desktop.csproj
> +    <PackageReference Include="fo-dicom" Version="5.1.0" Condition=" '$(Configuration)' != 'Debug' " />
This is a little weird? Shouldn't it just always reference the project, and not the NuGet package?
fo-dicom.Json doesn't seem to need this construct anyways.

2023-06-02 14:14 UTC, amoerie commented on Tests/FO-DICOM.Tests/FO-DICOM.Tests.csproj
> +    <TargetFrameworks>net462;net6.0;net6.0-windows;net7.0;net7.0-windows</TargetFrameworks>
You've added these target frameworks but they are never used in our CI setup.

2023-06-02 14:17 UTC, amoerie commented on Platform/FO-DICOM.Imaging.Desktop/FO-DICOM.Imaging.Desktop.csproj
> +    <Folder Include="Properties\" />
I think you can remove this

2023-06-02 14:30 UTC, timothylcooke commented on Platform/FO-DICOM.Imaging.Desktop/FO-DICOM.Imaging.Desktop.csproj
> +    <PackageReference Include="fo-dicom" Version="5.1.0" Condition=" '$(Configuration)' != 'Debug' " />
I wasn't sure. I would imagine you're right. TBH, I've never built a nuget package that references another Nuget package, and I wanted to make sure it was right. I can test this over the weekend.

2023-06-02 14:32 UTC, timothylcooke commented on Platform/FO-DICOM.Imaging.Desktop/FO-DICOM.Imaging.Desktop.csproj
> +    <Folder Include="Properties\" />
To be clear, you think I can remove the Properties folder?

2023-06-02 14:43 UTC, timothylcooke commented on Tests/FO-DICOM.Tests/FO-DICOM.Tests.csproj
> +    <TargetFrameworks>net462;net6.0;net6.0-windows;net7.0;net7.0-windows</TargetFrameworks>
All these targets do in effect is actually test the WPF/WinForms-specific tests in net6.0/net7.0, but those won't compile without explicitly targeting `-windows`. This also requires the `#if NET462 || WINDOWS` changes in the unit test files. Those tests are already run in net462 and they do pass when I run the tests locally. I have no experience in GitHub CI, but I'd be happy to look into it. Is it just as simple as adding entries in [.github/workflows/build.yml](https://github.com/fo-dicom/fo-dicom/blob/development/.github/workflows/build.yml)?

2023-06-02 14:49 UTC, timothylcooke commented on Tests/FO-DICOM.Tests/FO-DICOM.Tests.csproj
> +    <TargetFrameworks>net462;net6.0;net6.0-windows;net7.0;net7.0-windows</TargetFrameworks>
Also, given that your CI runs in Windows, is it fair to remove the `net6.0` and `net7.0` targets in favor of `net6.0-windows` and `net7.0-windows`, or should I keep the `net6.0` and `net7.0` targets for those running tests on non-Windows OSs?

2023-06-02 17:26 UTC, timothylcooke commented on Tests/FO-DICOM.Tests/FO-DICOM.Tests.csproj
> +    <TargetFrameworks>net462;net6.0;net6.0-windows;net7.0;net7.0-windows</TargetFrameworks>
It just occurred to me that there's another option: we can leave the targets in the csproj, but in CI, we can drop `net6.0` in favor of `net6.0-windows` (same for net7.0). The net effect is just that we add a few unit tests. I see no reason to test `net6.0` at all if you're already testing `net6.0-windows`.

2023-06-05 06:24 UTC, amoerie commented on Platform/FO-DICOM.Imaging.Desktop/FO-DICOM.Imaging.Desktop.csproj
> +    <Folder Include="Properties\" />
Yes, and also the reference to it from the csproj.

2023-06-05 06:26 UTC, amoerie commented on Tests/FO-DICOM.Tests/FO-DICOM.Tests.csproj
> +    <TargetFrameworks>net462;net6.0;net6.0-windows;net7.0;net7.0-windows</TargetFrameworks>
For me personally, I'd be fine switching the target frameworks of the unit tests to net6.0-windows and net7.0-windows since that's how we use them today anyway (in CI and on my machine).
We can always reintroduce net7.0 (or future versions) if we want to test on linux, but I'd be surprised if that would work without changing any code, since linux is case sensitive for example.

2023-06-05 06:28 UTC, amoerie commented on Platform/FO-DICOM.Imaging.Desktop/FO-DICOM.Imaging.Desktop.csproj
> +    <PackageReference Include="fo-dicom" Version="5.1.0" Condition=" '$(Configuration)' != 'Debug' " />
I think it's sufficient to simply reference the project. In the csproj of FO-DICOM.Core there is a "PackageId" property, I assume that "dotnet pack" understands this as a nuget dependency that way.

2023-06-05 06:30 UTC, amoerie requested changes
Changes requested, see individual comments :-)

2023-06-06 15:19 UTC, timothylcooke commented on Platform/FO-DICOM.Imaging.Desktop/FO-DICOM.Imaging.Desktop.csproj
> +    <PackageReference Include="fo-dicom" Version="5.1.0" Condition=" '$(Configuration)' != 'Debug' " />
@amoerie You were right. ProjectReference does the trick.

2023-06-06 15:21 UTC, timothylcooke commented on Tests/FO-DICOM.Tests/FO-DICOM.Tests.csproj
> +    <TargetFrameworks>net462;net6.0;net6.0-windows;net7.0;net7.0-windows</TargetFrameworks>
I removed net6.0 and net7.0 targets and moved the CI tests to net6.0-windows and net7.0-windows.

2023-06-06 15:21 UTC, timothylcooke commented on Platform/FO-DICOM.Imaging.Desktop/FO-DICOM.Imaging.Desktop.csproj
> +    <Folder Include="Properties\" />
Definitely can remove it. Thanks.

2023-06-06 15:24 UTC, timothylcooke commented
@amoerie I made the requested changes, and even added to the changelog and contributors.

Also, I created a new branch ([timothylcooke:fix-1318-desktop-net6](https://github.com/timothylcooke/fo-dicom/tree/fix-1318-desktop-net6)) that does everything in this PR in a single commit. Not sure how you want me to handle that: should I close this PR and make a new one?

2023-06-06 15:52 UTC, timothylcooke commented
Superceded by #1610

2023-06-06 15:52 UTC, closed without merging