Enable Microsoft Code Analysis
fo-dicom/fo-dicom pull request #1782
Opened 2024-05-02 11:05 UTC by amoerie

Fixes #1781

#### Checklist
- [x] The pull request branch is in sync with latest commit on the *fo-dicom/development* branch
- [x] I have updated API documentation
- [x] I have included unit tests
- [ ] ~~I have updated the change log~~
- [x] I am listed in the CONTRIBUTORS file

#### Changes proposed in this pull request:
- Enable CodeAnalysis "Minimum" = the most basic set of checks that Microsoft deemed as essential. We can dial it up to "Recommended" later
- I manually edited the .editorconfig to set the severity of several reliability and performance related checks to "Warning". For example, the "ConfigureAwait" check was not part of the "Minimum" set, so I had to enable this separately.
- Fix various warnings that surfaced after turning on the analysis.

2024-05-02 11:07 UTC, amoerie commented on FO-DICOM.Core/Network/PDU.cs
> +            RawPDU pdu = null;
Small note here: "await using" is compiler syntax sugar for `DisposeAsync` being called inside an automatically generated `finally` block.
Unfortunately there is no easy way to say "also add `ConfigureAwait(false)`", so this syntax sugar needed to be unwrapped manually. 

I could also suppress the warning here, since the method `RawPDU.DisposeAsync` doesn't actually do anything async for now, but that felt more dangerous.

2024-11-24 19:27 UTC, mrbean-bremen approved these changes
Finally got around to review this - I had ignored this before as I thought it would be out of my comfort zone, but the changes are actually quite straightforward (except for the `DisposeAsync ` stuff), and mostly related to slight performance improvements.
I didn't see any breaking changes, and fixing warnings (and turning them into errors) is always a good thing (I did the same recently in C++ code), so I think this is ready to be merged.

2024-11-24 19:27 UTC, mrbean-bremen commented on FO-DICOM.Core/Serialization/DicomJson.cs
>              var conv = JsonSerializer.Serialize(dataset, options);
You actually got a warning here because of the missing cache? Interesting...

2024-11-24 19:31 UTC, mrbean-bremen reviewed
There are of course the failing tests (I guess because of changes that came after that - they seem all like triggered by warnings that are now errors), and the missing merge, so not really ready to merge yet, but the changes look nevertheless good to me.

2024-11-25 07:09 UTC, gofal commented on FO-DICOM.Core/Serialization/DicomJson.cs
>              var conv = JsonSerializer.Serialize(dataset, options);
sure, why not. Warnings are just "suggestions" of the compiler. they may vary from compiler-version to compiler version. Warnings are - in contrast to errors - not something deterministic, rather suggestions. And they may vary a lot. You even get some warings from roslyn, or also from some plugins like ReSharper etc...

2024-11-25 07:26 UTC, gofal commented
> fixing warnings (and turning them into errors) is always a good thing

Fixing warnings is always a good thing. When working on some issue and a story, then you always should notice and rething the warnings that the compiler, your IDE and your plugins tell you at that point. But beware: Even if warnings are mostly fine, they are not always right (we all are in medical field, so take it like AI-findings: even if mostly fine, you always have to rething it yourself. It is a very bad idea, to copy all AI findings into reports automatically)

Turning warnings into errors on the other side is a bad idea. specially on a shared project with various IDEs where we all have different warnings. On your own project (or your company where everyone has the same), then you migt do that, and you might mess up the code with #pragma ignore code, to get rid of false warnings. But there is a reason, why compilers have two different kind of messages: errors and warnings. Automatically turning warnings into errors just ignores this distingtion, doesn't it? For errors you have to react. For Warnings you have to think about it and apply it or also refuse to apply it - depending on the scenario.

We humans should be smarter than compilers. They should help us, but we should not subjugate ourselfs the toolings. And doing such a mass-PR across all the project, just because getting rid of warnings is not valuable in my opinion.

2024-11-25 07:27 UTC, gofal requested changes
reject

2024-11-25 08:02 UTC, mrbean-bremen commented
Two things. First, I think turning _some_ or even most warnings into errors is a good thing, because many warnings point to possible real issues. Unfortunately, the MS compiler does not allow this, as far as I know (correct me if I'm wrong - maybe this is only true for the C++ compiler). One possibility is to convert warnings that we don't want to have into suggestions, but that's also not nice. 

I agree with your point that we should not force users of fo-dicom to use the same policy, though I was under the impression that this will not be the case - maybe I'm wrong. Also I wasn't aware that fo-dicom can use different compilers (the IDE does not matter here, only the compiler). But if that were the case, wouldn't they have other compiler settings anyway?

That being said, I agree that at the current stage it is probably not a good idea to turn warnings into errors, but I think that most of the changes in this PR make sense anyway. Most changes are performance improvements, and the changes also help to get used to the proper usage of the APIs. My suggestion would be to retain these changes, but not change warnings to errors (though I still see this as a worthy goal). Also we should probably disable some more warnings for all tests, so we don't need these ugly warning suppression attributes there. 

Note that I maybe biased here by my own recent experience. We had tens of thousands of warnings in our C++ code which nobody had really looked at, and which have been very annoying, but after turning the warnings into errors and fixing them (which was surprisingly easy in the end), the state is much better and new warnings much easier to see and handle now.

What do you think?

2024-11-25 13:35 UTC, gofal commented
Well, .net compiler Roslyn is very different to c++ compiler. The roslyn is open and provides API, so it is easy to jump in and for example add code generators depending on properties, or to add validators, inject code analizers and raise errors, warnings or suggestions.
The warings all have some Code. The ones, that roslyn throws natively, all start with "CS" like "CS0109: The member '{0}' does not hide an accessible member. The new keyword is not required.".  They are really about compiling c# into IL (https://gist.github.com/thomaslevesque/43e4950a65961e2194e4ce082d64bc31)
And then Visual Studio also has some warings injected, they are rather about coding formatting. their codes start with "IDE". Many other IDEs of course also use these error/waring codes. Like "IDE0001: Simplify name" when unnecessary namespaces can be removed.
And then you can add some code analysis, you can have plugins like the famous Resharper. You can have SonarLint/SonarCube etc. All of then injecting, anlayzing code and raising warings, suggestions (and if yo configure, thenalso errors).

You remember the PR https://github.com/fo-dicom/fo-dicom/pull/1885?
![image](https://github.com/user-attachments/assets/6a7d35a3-e702-4048-9baf-b0c930eab043)
Well, with "TreatWaringsAsError", then fo-dicom would propably not have compiled on his machine.

> Unfortunately, the MS compiler does not allow this, as far as I know 

Sure, you can do so. In .editorconfig you can change the severity of each single errorcode to any value you want (none, error, warning, suggestion,..). Every IDE, which supports .editorconfig will then pass these settings to the compiler.

I see, that we agree, that turning some certain warnings, where we think that this is super important, into a error by configuring .editorconfig file, could be a good idea and have some benefints. But this is then he Opt-In way. We say, which warnings should be treated as error. But I want to reject this pull request here, because it would be an Opt-Out way, turning all warings into errors and expecting to configure those away that are false positive.

And I really dislike this kind of huge pull request where code is changed in all the project and Risks for regressions are introduced, without any needs.

2024-11-25 14:30 UTC, mrbean-bremen commented
Thanks for the explanations!
I agree that the PR as is is a bit too large. Maybe adding separate PRs for separate warnings (without turning them into errors for now) would be a way to go.

2024-11-25 14:42 UTC, closed without merging

2024-11-27 08:12 UTC, pvrobays commented
> You remember the PR #1885? ![image](https://private-user-images.githubusercontent.com/6769246/389542706-6a7d35a3-e702-4048-9baf-b0c930eab043.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2OTM4NDcsIm5iZiI6MTczMjY5MzU0NywicGF0aCI6Ii82NzY5MjQ2LzM4OTU0MjcwNi02YTdkMzVhMy1lNzAyLTQwNDgtOWJhZi1iMGM5MzBlYWIwNDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjdUMDc0NTQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGI3Y2Q1YWEzMjhjZDc5YTZjOGZhMDI0Yzk0MjJjYTA1MWYwMDA2YzNmNmY3MzU0MjI1ZDhhYmUyODg1MTU5NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.mrfANIwZQeSkS_Cwn09z0cMOwc89dysfTfOqZvbeGko) Well, with "TreatWaringsAsError", then fo-dicom would propably not have compiled on his machine.

Just FYI, it wouldn't have. That's a plugin which doesn't use compiler warnings, just shows information on the method level about cognitive complexity within the IDE.

In most of my shared projects I also use 'TreatWarningsAsError' because for me on the one hand this makes the feedback loop shorter, but more importantly helps junior devs in a diverse team to improve their code quality. The fact that 5% of the warnings are false positives and have to be surrounded with the ugly #pragma comment, is just an extra confirmation for me that the dev who coded it at least actively thought about the warning instead of ignoring the warning during compilation.

I understand gofal's concerns, but nevertheless I'm sad to see this PR getting closed.

2024-11-28 06:33 UTC, mrbean-bremen commented
@amoerie - I too would not like it if that effort would go wasted. I also understand gofal's concern, even if I don't share it, but I think it would still make sense to fix most of these warnings, even if not turning warnings into errors. Handling the warnings separately (or in small batches) in separate PRs would be a way to go in my opinion, if you still want to do this. 
We could even do something like add a settings that turns these warnings into errors and build with this setting in the CI, but deploy without it, if that is what it takes.

We also had warnings handled as errors in our C# projects (also the one that used fo-dicom, even if I don't work there anymore), and done the same in the various C++ projects I have been working with. In the end, this always turned out to be the cleaner solution, especially with diverse people contributing to the code over the years, as already mentioned by @pvrobays.

2024-11-28 07:00 UTC, gofal commented
I had made it very clear when the issue  #1781 was opened, that it is a good idea to turn on code analysis, but that turning warings to error is a concern. Sadly he ad opened a huge PR and put work into it without previously opening the issue. but even then afterwards he continued to commit. 
Well, the fact that he just did all this, does not solve the concern, or should it? We had some discussions about huge refactoring-PRs in advance, so he should have known.

Sure there are a lot of different strategies how to organize a Repro. My goal here is not to have a strict repro, but to provide some code free for everyone and easy to build and use for as many users as possible. Thats why still .netstandard2.0 is supported and not only .net8 or things like that. And I am glad that you understand my concerns. There is a good reason why there are two kinds of feedback from compiler and co: Error and Warning. And microsoft makes it very comfortable to configure this all, and to turn some warings into erors if prefered. But turning all into error by default is just an issue.

You both seem to come from the c++ world. And yeah, there it makes sense. C++ is a language that has much more pitfalls, where you easily get the off-by-one things and pointers leading to nowhere. and the compiler defines that if there is an issue then the outcome is indefined, so you never can rely on clean error messages, but if you have some error, then literally anything can happen. So in c++ is is a good idea to take warings very seriously and to be very defensive when coding. When working at Borland I also had to code in c++, so I know that all.
But see, c# is very very different from that. This is a managed language, the risks is much lower. Here the warings are really just "hints" and "suggestions".

2024-11-28 07:25 UTC, mrbean-bremen commented
You are right about C++ vs C# - the warnings here are mostly about efficiency (and formatting, if you switch these on), and coming from C++ this probably looks different (I actually come from C, where is also a lot of room to shoot yourself in the foot).

I also agree about large PRs (I don't like them either), thus my suggestion to make separate PRs for specific warnings without turning them into errors (though I'm not against turning some of them into errors). 

Unrelated - you have worked at Borland? That's nice, I have been a big fan at the time! Turbo Pascal 3 actually has been the first language with an IDE (kind of) that I have used, and I have also used Delphi for quite some time, and Borland C++.

2024-11-28 07:50 UTC, gofal commented
I also knew Borland and liked it since I have been a child. By first IDE was GW-Basic, but Turbo Pascal then was the next one and was my prefered language for long time.
But I actually did not work on the compilers, but rather on devops applications. The Borland Silk Performer (meanwhile bought and now calles MicroFocus Silk Performer), a performance and load testing application.

2024-11-28 09:35 UTC, amoerie commented
@mrbean-bremen 

> if you still want to do this

Honestly, I don't.